name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: "14.x"

    - name: Install the Dependencies
      run: npm install

    - name: Build the Application
      run: npm run build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
